mrc-2165 Update orderly web to use new interface
vimc/orderly-web pull request #295
Opened 2021-02-02 16:27 UTC by mwoodbri

- [ ] Check tests
- [ ] Check existing report running functionality
- [ ] Update API docs
- [ ] Add Redis to dependency scripts

2021-02-03 13:32 UTC, EmmaLRussell approved these changes
Looks good to me. 

It's possible this change might also impact the diagnostic task runner - I'll check that. Might mean yet another PR to coordinate.

2021-02-12 16:20 UTC, richfitz requested changes

2021-02-12 16:20 UTC, richfitz commented on config/orderly_server_version
> +vimc-4192
This just needs unpinning now, once the orderly.server build has passed

2021-02-12 17:13 UTC, richfitz approved these changes

2021-02-12 17:13 UTC, merged