mrc-2247 Endpoint for queue status
vimc/orderly-web pull request #322
Opened 2021-03-16 16:37 UTC by EmmaLRussell

_Before submitting please review
the [PR checklist](https://mrc-ide.myjetbrains.com/youtrack/articles/RESIDE-A-13/Pull-Request-guidelines)_

2021-03-17 12:23 UTC, mwoodbri requested changes
All looks good - apart perhaps from documentation?

2021-03-17 12:23 UTC, mwoodbri commented on docs/spec/QueueStatus.schema.json
> +        "required": ["key", "status", "name", "version"],
Presumably this spec is inherited from orderly.server but `version` being `required` doesn't seem consistent with `spec.md` or the tests below

2021-03-17 12:23 UTC, mwoodbri commented on docs/spec/spec.md
> +[
Integration test below and schema above suggest that this should be wrapped with `{tasks: [ ... ]}`?

2021-03-17 16:09 UTC, EmmaLRussell commented
> All looks good - apart perhaps from documentation?

Agreed, this is a bit off in the orderly server docs which I mindlessly copied it from!

2021-03-17 18:07 UTC, mwoodbri approved these changes

2021-03-18 17:00 UTC, Nicolas-Dolan reviewed
Looks good. I have no changes to suggest.

2021-03-18 18:32 UTC, merged