mrc-2150 Add 'View log' link on run report tab
vimc/orderly-web pull request #337
Opened 2021-04-23 08:46 UTC by Nicolas-Dolan

_Before submitting please review
the [PR checklist](https://mrc-ide.myjetbrains.com/youtrack/articles/RESIDE-A-13/Pull-Request-guidelines)_

2021-04-23 14:19 UTC, EmmaLRussell requested changes
Looks good! Just a couple of comments. 

Seem to have rogue top-level package.json and package-lock.json files here, can we lose those? 

> Possibly, we could append the time/date the run was started to the list component after a value is selected to further specify which report we have run and differentiate it from report runs with the same name.

I think the trouble is that we aren't able to display both report name and time separately styled in the input with our current implementation, so mrc-2333 still stands. But what you've done here is good for keeping the view consistent among all ways of selecting running reports.

2021-04-23 14:19 UTC, EmmaLRussell commented on src/app/static/src/js/components/reportLog/runningReportsList.vue
> +                    return this.reports.map(report => {
Feels like using `filter` would be more natural here than `map

2021-04-23 14:19 UTC, EmmaLRussell commented on src/app/static/src/js/components/reportLog/runningReportsList.vue
> +            initialInputValue(){
This maybe shouldn't be a computed value if it's only every used to generate an initial query value on mount - could just move this code to `mounted` and set `query` from there directly.

2021-04-23 14:19 UTC, EmmaLRussell commented on src/app/static/src/js/components/runReport/runReport.vue
> +                        <a @click.prevent="checkStatus" href="#">Check status</a> /
I think we can get rid of the `Check status` link now - it was only every a stopgap until the running reports stuff, and this ticket, was done.

2021-04-23 14:19 UTC, EmmaLRussell commented on src/app/static/src/tests/components/runReport/runReport.test.ts
> +                expect(wrapper.emitted("changeTab")).toBeTruthy();
```suggestion
                expect(wrapper.emitted("changeTab").length).toBe(1);
```

2021-04-26 11:32 UTC, mwoodbri approved these changes
Works very nicely.

Questionable whether we need to retain `runningStatus` at all but not a major issue.

One other stylistic suggestion but can be merged as-is.

2021-04-26 11:32 UTC, mwoodbri commented on src/app/static/src/js/components/reportLog/runningReportsList.vue
> +                this.query = this.reports.filter(report => report.key === this.initialSelectedKey)[0]["name"]
`find()` is more idiomatic (and efficient: it returns first match without filtering the whole array):
```suggestion
                this.query = this.reports.find(report => report.key === this.initialSelectedKey).name
```

2021-05-11 14:46 UTC, mwoodbri requested changes
Good job!

Please just remove `chromedriver_linux64.zip` and request re-review - I'll be very happy to approve/merge.

2021-05-11 16:31 UTC, mwoodbri approved these changes

2021-05-11 16:38 UTC, EmmaLRussell approved these changes

2021-05-12 10:12 UTC, merged