mrc-2898 Return start time for running workflow report when available
vimc/orderly-web pull request #441
Opened 2022-03-14 09:32 UTC by LekanAnni

_Before submitting please review
the [PR checklist](https://mrc-ide.myjetbrains.com/youtrack/articles/RESIDE-A-13/Pull-Request-guidelines)_

2022-03-17 10:44 UTC, EmmaLRussell commented
> There are assumptions that the startTime may get overwritten in the process of polling, I have not included this assumption in this solution as I do not clearly understand.

The issue is that orderly server's knowledge of report start times is kept in redis, which is torn down on redploy - so is essentially temporary. Any request to  OS of a start time for a report run before the last redeploy will return null (I think). However, OrderlyWeb may have saved the report's start time before redeploy - so it just means that we should be careful not to overwrite a non-null start time in the orderly web table with null - in fact we should never overwrite once we have a value since it shouldn't change.  

Of course, we might not request a report's start time until after a redploy if user has not gone to the logs before the redeploy, in which case start time just won't be available to view. I think we've said we can live with that possibility for now.

2022-03-17 11:06 UTC, EmmaLRussell requested changes
Looks good, but I think we do need to deal with the overwrite issue, and I don't think we should use 'now' as a fallback.

2022-03-17 11:06 UTC, EmmaLRussell commented on src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/db/repositories/WorkflowRunReportRepository.kt
> +                .set(ORDERLYWEB_WORKFLOW_RUN_REPORTS.DATE, Timestamp.from(startTime))
Should only do this if value is not null, to avoid overwriting with null post redis redeploy

2022-03-18 15:25 UTC, hillalex approved these changes

2022-03-18 16:16 UTC, EmmaLRussell approved these changes
Great, thanks!

2022-03-18 16:17 UTC, merged