mrc-2999 add run report app with tabs under new vuex route
vimc/orderly-web pull request #448
Opened 2022-03-16 14:08 UTC by hillalex

2022-03-16 14:10 UTC, hillalex commented on src/app/static/src/js/components/documents/fileIcon.vue
> -        name: "fileIcon"
Unrelated to changeset, guess this is cos I ran `npm run lint -- --fix` and it fixed this warning.

2022-03-16 15:38 UTC, LekanAnni requested changes
Looks great, 

Some missing tests such as mutation test.

2022-03-16 17:31 UTC, EmmaLRussell reviewed
LGTM, just one query on the template test

2022-03-16 17:31 UTC, EmmaLRussell commented on src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/unit_tests/templates/vuex/RunReportPageTests.kt
> +        doc.select("#runReportTabsVueApp").select("run-report-tabs")
I don't think the select will cause the test to fail if no element is found, you'll just get an empty list.
```suggestion
        val tabs = doc.select("#runReportTabsVueApp").select("run-report-tabs")
        assertThat(tabs.count()).isEqualTo(1)
```

2022-03-18 16:11 UTC, LekanAnni approved these changes
LGTM 👍

2022-03-18 16:18 UTC, EmmaLRussell approved these changes

2022-03-18 16:18 UTC, merged