mrc-2996 Use Hub4j client for GitHub auth
vimc/orderly-web pull request #451
Opened 2022-03-16 23:33 UTC by EmmaLRussell

_Before submitting please review
the [PR checklist](https://mrc-ide.myjetbrains.com/youtrack/articles/RESIDE-A-13/Pull-Request-guidelines)_

2022-03-21 10:28 UTC, LekanAnni commented
I am getting `Failed to retrieve or validate credentials: User is not a member of GitHub org vimc-auth-test` error message. I'm sure I am a member of vimc-auth-test but still getting this error. 

Maybe I am not a member.

2022-03-21 12:24 UTC, Nicolas-Dolan approved these changes
Works as described

2022-03-21 12:49 UTC, LekanAnni requested changes
LGTM 

See inline for some minor suggestions.

2022-03-21 12:49 UTC, LekanAnni commented on src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/security/GithubApiClientAuthHelperTests.kt
> +        assertSame(mockUser, result)
I think j`unit.framework.Assert` is depreciated

2022-03-21 12:49 UTC, LekanAnni commented on src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/security/providers/GithubApiClientAuthHelper.kt
> +        if (!teamName.isEmpty() && !userBelongsToTeam(org, teamName, user!!))
```suggestion
        if (teamName.isNotEmpty() && !userBelongsToTeam(org, teamName, user!!))
```

2022-03-21 12:49 UTC, LekanAnni commented on src/app/src/main/kotlin/org/vaccineimpact/orderlyweb/security/providers/GithubApiClientAuthHelper.kt
> +        return result
```suggestion
        return user!!.email ?: getEmailForUser()
```

2022-03-21 12:49 UTC, LekanAnni commented on src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/GithubAuthenticationTests.kt
> +    val testUserPAT = "dyw4x210375dauDALEtMVdvjypgs8RuGcY8H_phg".reversed()
```suggestion
    private val testUserPAT = "dyw4x210375dauDALEtMVdvjypgs8RuGcY8H_phg".reversed()
```

2022-03-21 12:49 UTC, LekanAnni commented on src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/GithubAuthenticationTests.kt
>      val JSONValidator = JSONValidator()
```suggestion
    private val jsonValidator = JSONValidator()
```

2022-03-23 10:40 UTC, hillalex reviewed
This all looks great, but am I right in thinking we're still missing a custom config test for the case where both org and team membership are required? Or am I just failing to spot it?

2022-03-23 10:50 UTC, EmmaLRussell commented
> This all looks great, but am I right in thinking we're still missing a custom config test for the case where both org and team membership are required? Or am I just failing to spot it?

No, I think we've got those. 
Web portal tests from here: https://github.com/vimc/orderly-web/blob/master/src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/GithubWebTests.kt#L96
API tests from here: https://github.com/vimc/orderly-web/blob/master/src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/GithubAuthenticationTests.kt#L92

Are those what you mean?

2022-03-24 12:39 UTC, hillalex commented
> No, I think we've got those. Web portal tests from here: https://github.com/vimc/orderly-web/blob/master/src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/GithubWebTests.kt#L96 API tests from here: https://github.com/vimc/orderly-web/blob/master/src/customConfigTests/src/test/kotlin/org/vaccineimpact/orderlyweb/customConfigTests/GithubAuthenticationTests.kt#L92
> 
> Are those what you mean?

Ah perfect, thanks! I thought I rememebered you adding them but just couldn't spot them

2022-03-24 12:39 UTC, hillalex approved these changes

2022-03-24 21:05 UTC, hillalex commented
Tests now failing because of the `orderly.server` changes to the run workflows endpoint. Once this PR is merged these will pass again: https://github.com/vimc/orderly-web/pull/454

2022-04-22 13:44 UTC, merged