mrc-3401 fix bug in spec
vimc/orderly-web pull request #471
Opened 2022-07-14 14:00 UTC by hillalex

The spec/schema for `GET reports/:name/versions/:version` was wrong. This updates the integration test to actually pick this up (see https://github.com/vimc/orderly-web/pull/471/commits/e3be3248487ea09b8122ce76175e6f6aba8780c4 for failing test prior to schema change), and fixes the spec/schema so that it matches the behaviour of the endpoint.

2022-07-15 09:43 UTC, EmmaLRussell reviewed
Good stuff! Think there might be a couple of updates to make to the example in the docs?

2022-07-15 09:43 UTC, EmmaLRussell commented on docs/spec/spec.md
> +      ]
Shouldn't these be FileInfos?

2022-07-15 09:43 UTC, EmmaLRussell commented on docs/spec/spec.md
> +    "rdsSize": 559
```suggestion
    "csv_size": 751,
    "rds_size": 559
```

2022-07-15 13:35 UTC, LekanAnni requested changes
Looks good other than the suggestion, which makes me question how the test is passing. I perhaps you have to update orderlyR schema as well.

2022-07-15 13:35 UTC, LekanAnni commented on docs/spec/spec.md
> +      ]
```suggestion
      "files": [{name: "minimal", file:  "mygraph.png"]
```

2022-07-18 13:04 UTC, hillalex commented
> Looks good other than the suggestion, which makes me question how the test is passing. Perhaps you have to update orderlyR schema as well.

Thanks for spotting this (and @EmmaLRussell) - tests run against the schema but the spec is written by hand so unfortunately doesn't get verified by any tests. Actually in `montagu-api` we do have a task that parses the markdown and compares it to the schema, probably useful to introduce that here too: https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-3438

2022-07-19 08:30 UTC, LekanAnni approved these changes
LGTM 👍

2022-07-19 08:34 UTC, EmmaLRussell approved these changes

2022-07-19 09:42 UTC, merged